import { getSecuritySkillManifest } from "@/security-pack/catalog";
import type { CuratedSecurityProcedure, SecuritySkillId } from "@/security-pack/types";

const procedures: Record<SecuritySkillId, Omit<CuratedSecurityProcedure, "sourceSha256">> = {
  "auditing-mcp-servers-for-tool-poisoning": {
    id: "auditing-mcp-servers-for-tool-poisoning",
    title: "MCP Integration Review",
    lifecycle: "production",
    sourcePath: "skills/auditing-mcp-servers-for-tool-poisoning/SKILL.md",
    intent: "Review MCP server metadata before connection, without trusting server-provided descriptions as instructions.",
    userOutcome: "The user sees an inventory, risky wording, baseline drift, scope concerns, and a recommendation before approval.",
    workflow: [
      "Render an Integration Map or Security Console immediately.",
      "Acquire an explicitly selected MCP config or registered integration.",
      "Canonicalize server, transport, tool, prompt, resource, schema, and destination metadata.",
      "Run deterministic static checks against untrusted descriptions and schemas.",
      "Compare against an approved baseline only when one exists.",
      "Request explicit approval before saving a new baseline.",
    ],
    safetyBoundaries: [
      "No live SSRF probing in the default product.",
      "No loading of raw upstream Markdown into model context.",
      "No external scanner unless a reviewed adapter and disclosure are enabled.",
    ],
    capabilityRequirements: ["security.mcp.inventory", "security.mcp.static_review", "security.mcp.baseline_compare"],
    verificationRequirements: ["Tool definitions are hashable.", "Changed schemas are visible.", "Poisoning signals remain advisory evidence."],
    rollback: ["Delete or ignore a locally approved baseline after user approval.", "Disable `security_mcp_review`."],
    userFacingSurfaces: ["Integration Map", "Security Console", "Risk Register", "Approval Flow"],
    notes: ["The former mcp-scan path is not reproduced; any future scanner adapter must be version-detected and reviewed."],
  },
  "implementing-secret-scanning-with-gitleaks": {
    id: "implementing-secret-scanning-with-gitleaks",
    title: "Secret Scanning",
    lifecycle: "production",
    sourcePath: "skills/implementing-secret-scanning-with-gitleaks/SKILL.md",
    intent: "Scan a user-selected repository or directory with redacted output and no automatic remediation.",
    userOutcome: "The user sees scoped preflight, redacted findings, remediation guidance, and missing-tool setup status.",
    workflow: [
      "Render a Security Console immediately.",
      "Require a workspace root or selected directory.",
      "Preflight policy for read scope, temporary report location, executable adapter, and redaction.",
      "Use current Gitleaks command families: `git`, `dir`, or `stdin`.",
      "Parse JSON or SARIF into typed redacted findings.",
      "Delete temporary reports after parsing.",
    ],
    safetyBoundaries: [
      "Deprecated `gitleaks detect` and `gitleaks protect` are not used.",
      "No repository history rewrite, hook install, CI edit, or allowlist write happens automatically.",
      "Raw secret values are never persisted or displayed.",
    ],
    capabilityRequirements: ["security.secrets.scan.readonly", "security.secrets.parse_gitleaks"],
    verificationRequirements: ["Missing executable returns `tool_missing`.", "Unsupported versions return `tool_version_unsupported`.", "Findings contain redacted previews only."],
    rollback: ["Cancel scan process.", "Delete ephemeral report files.", "Disable `security_secret_scan`."],
    userFacingSurfaces: ["Security Console", "Evidence Board", "Risk Register", "Approval Flow"],
    notes: ["A limited heuristic fallback can label suspicious strings, but it is not equivalent to Gitleaks."],
  },
  "performing-threat-modeling-with-owasp-threat-dragon": {
    id: "performing-threat-modeling-with-owasp-threat-dragon",
    title: "Threat Modeling",
    lifecycle: "production",
    sourcePath: "skills/performing-threat-modeling-with-owasp-threat-dragon/SKILL.md",
    intent: "Build and revise a neutral FlowSurface threat model without requiring Threat Dragon.",
    userOutcome: "The user gets editable entities, flows, trust boundaries, prioritized threats, mitigations, assumptions, and a decision brief.",
    workflow: [
      "Render an Infinite Canvas immediately.",
      "Represent actors, processes, stores, external entities, data flows, trust boundaries, assets, and assumptions.",
      "Apply STRIDE by default and LINDDUN where privacy data is present.",
      "Recalculate affected threats when a flow, boundary, or privilege changes.",
      "Separate confirmed evidence from inferred architecture.",
    ],
    safetyBoundaries: ["No security claim stronger than evidence.", "Threat Dragon import/export remains optional.", "No external install required."],
    capabilityRequirements: ["security.threat_model.create", "security.threat_model.recalculate"],
    verificationRequirements: ["Schema round trip works.", "Assumptions are preserved.", "Risk scores update deterministically."],
    rollback: ["Return to the previous model revision.", "Disable `security_threat_model`."],
    userFacingSurfaces: ["Infinite Canvas", "Risk Register", "Review Room", "Decision Brief"],
    notes: ["Threat frameworks are decision aids, not compliance certification."],
  },
  "detecting-ai-model-prompt-injection-attacks": {
    id: "detecting-ai-model-prompt-injection-attacks",
    title: "Prompt-Injection Signals",
    lifecycle: "internal",
    sourcePath: "skills/detecting-ai-model-prompt-injection-attacks/SKILL.md",
    intent: "Mark suspicious untrusted content while keeping policy authoritative.",
    userOutcome: "Untrusted content is labeled with reason codes, provenance, confidence, and redacted snippets.",
    workflow: [
      "Normalize Unicode.",
      "Detect bidi controls and invisible characters.",
      "Look for instruction override, role impersonation, tool coercion, exfiltration, and encoded-content signals.",
      "Pass structured advisory signals into policy and orchestration.",
    ],
    safetyBoundaries: ["No 700 MB model classifier in MVP.", "Signals are advisory and never the sole authorization boundary."],
    capabilityRequirements: ["security.prompt_injection.inspect"],
    verificationRequirements: ["Benign discussion does not block.", "Suspicious retrieved content keeps provenance."],
    rollback: ["Disable `security_prompt_injection_detection`."],
    userFacingSurfaces: ["Security Console", "Evidence Board"],
    notes: ["The detector does not silently delete user content."],
  },
  "implementing-llm-guardrails-for-security": {
    id: "implementing-llm-guardrails-for-security",
    title: "LLM Tool Guardrails",
    lifecycle: "internal",
    sourcePath: "skills/implementing-llm-guardrails-for-security/SKILL.md",
    intent: "Validate input, context, output, and proposed tool intent before policy preflight and execution.",
    userOutcome: "Developers can inspect redacted guard traces and see why a tool intent was blocked or sent to approval.",
    workflow: [
      "Normalize user input.",
      "Classify untrusted context as data.",
      "Redact sensitive values before logs or cloud calls.",
      "Validate model output schemas.",
      "Evaluate tool intent through deterministic policy.",
    ],
    safetyBoundaries: ["No NeMo, Guardrails AI, Presidio, or Python service is added.", "Unknown security-relevant fields fail closed."],
    capabilityRequirements: ["security.guardrails.inspect", "security.tool_intent.validate"],
    verificationRequirements: ["Invalid tool schemas fail.", "Policy remains authoritative.", "Sensitive traces are redacted."],
    rollback: ["Disable `security_llm_guardrails`."],
    userFacingSurfaces: ["Security Console", "Approval Flow"],
    notes: ["Framework adapters can be added later behind the provider-neutral interface."],
  },
  "analyzing-sbom-for-supply-chain-vulnerabilities": {
    id: "analyzing-sbom-for-supply-chain-vulnerabilities",
    title: "SBOM Analysis",
    lifecycle: "experimental",
    sourcePath: "skills/analyzing-sbom-for-supply-chain-vulnerabilities/SKILL.md",
    intent: "Parse existing CycloneDX or SPDX data locally before any optional external vulnerability lookup.",
    userOutcome: "The user sees normalized components, dependency evidence, vulnerability metadata, and provider limitations.",
    workflow: ["Import SBOM JSON.", "Normalize components and package URLs.", "Attach imported vulnerability evidence if present.", "Label absence of findings as unknown, not safe."],
    safetyBoundaries: ["No network queries without disclosure and approval.", "No auto-install of Syft or Grype."],
    capabilityRequirements: ["security.sbom.parse"],
    verificationRequirements: ["CycloneDX and SPDX fixtures parse.", "Invalid documents fail with structured errors."],
    rollback: ["Disable `security_sbom_analysis`."],
    userFacingSurfaces: ["Evidence Matrix", "Risk Register", "Quality Dashboard"],
    notes: ["Experimental and off by default."],
  },
  "implementing-sigstore-for-software-signing": {
    id: "implementing-sigstore-for-software-signing",
    title: "Sigstore Verification",
    lifecycle: "experimental",
    sourcePath: "skills/implementing-sigstore-for-software-signing/SKILL.md",
    intent: "Verify artifact signatures and identities without enabling signing or publication.",
    userOutcome: "The user sees verification result, expected identity checks, issuer, digest, timestamp, and trust-policy gaps.",
    workflow: ["Require an artifact or digest.", "Preflight Cosign availability and version.", "Verify signature evidence.", "Compare issuer and subject to explicit trust policy."],
    safetyBoundaries: ["No OIDC token request.", "No signing, key creation, publication, or transparency-log submission initiated by the app."],
    capabilityRequirements: ["security.sigstore.verify"],
    verificationRequirements: ["Wrong identity and wrong issuer fail.", "Cryptographic validity is not treated as trust by itself."],
    rollback: ["Disable `security_sigstore_verification`."],
    userFacingSurfaces: ["Security Console", "Evidence Board", "Approval Flow", "Audit Trail"],
    notes: ["Experimental and off by default."],
  },
  "implementing-supply-chain-security-with-in-toto": {
    id: "implementing-supply-chain-security-with-in-toto",
    title: "in-toto Verification",
    lifecycle: "experimental",
    sourcePath: "skills/implementing-supply-chain-security-with-in-toto/SKILL.md",
    intent: "Verify existing layouts and link metadata without generating keys or attestations.",
    userOutcome: "The user sees authorized functionary, threshold, expiration, step, and hash-chain failures with exact reasons.",
    workflow: ["Parse layout and links.", "Check step uniqueness and expiry.", "Check functionary and threshold rules.", "Check material and product hash-chain continuity."],
    safetyBoundaries: ["No key generation.", "No layout signing.", "No attestation publication."],
    capabilityRequirements: ["security.in_toto.verify"],
    verificationRequirements: ["Replay, duplicate step, threshold, and hash-chain fixtures fail deterministically."],
    rollback: ["Disable `security_in_toto_verification`."],
    userFacingSurfaces: ["Integration Map", "Evidence Board", "Risk Register", "Audit Trail"],
    notes: ["Successful verification does not prove vulnerability-free software."],
  },
};

export function getCuratedSecurityProcedure(id: SecuritySkillId): CuratedSecurityProcedure {
  const procedure = procedures[id];
  const manifest = getSecuritySkillManifest(id);
  if (!procedure || !manifest) {
    throw new Error(`Unknown Security Pack procedure: ${id}`);
  }

  return {
    ...procedure,
    sourceSha256: manifest.source.sourceSha256,
  };
}
